### ISSUE TITLE
Camera ASI715MC not found

### ISSUE THREAD

**Issue by TimmRuppert** [MPI-IS/camera_zwo_asi#5]
Hello,

it seems like my camera ASI715MC does not get found. Any ideas what might be wrong?

- I installed this package via pip
- I installed the mentioned requirments via apt
- I installed the udev rule
- I am on Ubuntu 22.04 

**dmesg except**
```bash
[ 9993.815730] usb 3-3: new high-speed USB device number 14 using xhci_hcd
[ 9993.965351] usb 3-3: New USB device found, idVendor=03c3, idProduct=715d, bcdDevice= 0.00
[ 9993.965370] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 9993.965376] usb 3-3: Product: ASI715MC
[ 9993.965380] usb 3-3: Manufacturer: ZWO
```

**lsusb and bus rights**
```bash
$ lsusb 
Bus 003 Device 014: ID 03c3:715d ZWO ASI715MC
..
$ ls -lah  /dev/bus/usb/003/014 
crw-rw-rw- 1 root root 189, 269 Jul 16 10:07 /dev/bus/usb/003/014
$ cat /sys/module/usbcore/parameters/usbfs_memory_mb
200

```

The ASI715MC is plugged in on a USB 3.0 port withthout any hub or similar. 

The command `zwo-asi-print` simply remains without any output while others fail (I assume the index errors is due tot the fact that the camera is simply not visible to this package)

```bash
zwo-asi-dump 
Traceback (most recent call last):
  File "/home/timm/.local/bin/zwo-asi-dump", line 8, in <module>
    sys.exit(dump())
  File "/home/timm/.local/lib/python3.10/site-packages/camera_zwo_asi/main.py", line 144, in dump
    camera = Camera(index)
  File "/home/timm/.local/lib/python3.10/site-packages/camera_zwo_asi/camera.py", line 27, in __init__
    super().__init__(index)
RuntimeError: ASI Camera: (camera index: 0)  (error code: 1: ASI_ERROR_INVALID_INDEX)

```

**Comment by TimmRuppert** [comment]
Update: Install from source does fix the issue. I assume the pypi might just be a bit outdated?
